# Generated by Django 6.0.6 on 2026-06-27 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', '-created_at'], name='products_pr_is_avai_8299d1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='products_pr_categor_f9fe54_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['farmer', '-created_at'], name='products_pr_farmer__20a951_idx'),
        ),
    ]
