# Generated by Django 6.0.6 on 2026-06-27 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='orders_orde_custome_413d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['farmer', '-created_at'], name='orders_orde_farmer__e83952_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
    ]
